DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Dealer;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Options;
